kind: pipeline
name: default
platform:
  arch: arm64
steps:
- name: docker
  image: plugins/docker
  settings:
    repo: registry.cn-hangzhou.aliyuncs.com/toyangdon/jodconverter-runtime
    use_cache: true
    tags:
      - latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
